### ISSUE TITLE
🤖 Sync error for commit 8cb214

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/crystal#593]
We hit an error trying to sync the latest commit (8cb214fe2f51d1f767e145bde2754c2a37475eb5) to the website.

The error was:
```
Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`exercism`.`user_track_viewed_exercise_approaches`, CONSTRAINT `fk_rails_5250bf18e8` FOREIGN KEY (`approach_id`) REFERENCES `exercise_approaches` (`id`))

/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `_query'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `block in query'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `handle_interrupt'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `query'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:632:in `block (2 levels) in raw_execute'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:631:in `block in raw_execute'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:630:in `raw_execute'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:96:in `raw_execute'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:47:in `execute'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:207:in `execute_and_free'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:73:in `block in exec_delete'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:72:in `exec_delete'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:181:in `delete'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `delete'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/persistence.rb:529:in `_delete_record'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/persistence.rb:1044:in `_delete_row'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/persistence.rb:1040:in `destroy_row'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/counter_cache.rb:176:in `destroy_row'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/locking/optimistic.rb:121:in `destroy_row'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/persistence.rb:680:in `destroy'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/callbacks.rb:439:in `block in destroy'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:107:in `run_callbacks'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:929:in `_run_destroy_callbacks'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/callbacks.rb:439:in `destroy'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/transactions.rb:294:in `block in destroy'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:314:in `transaction'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/transactions.rb:294:in `destroy'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/persistence.rb:696:in `destroy!'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/has_many_association.rb:124:in `each'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/has_many_association.rb:124:in `delete_records'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/collection_association.rb:390:in `remove_records'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/collection_association.rb:381:in `block in delete_or_destroy'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:314:in `transaction'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/transactions.rb:209:in `transaction'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/collection_association.rb:308:in `transaction'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/collection_association.rb:381:in `delete_or_destroy'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/collection_association.rb:179:in `delete'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/collection_association.rb:405:in `replace_records'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/collection_association.rb:243:in `block in replace'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:314:in `transaction'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/transactions.rb:209:in `transaction'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/collection_association.rb:308:in `transaction'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/collection_association.rb:243:in `replace'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/collection_association.rb:45:in `writer'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/associations/builder/association.rb:112:in `approaches='
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activemodel-7.0.4.3/lib/active_model/attribute_assignment.rb:49:in `public_send'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activemodel-7.0.4.3/lib/active_model/attribute_assignment.rb:49:in `_assign_attribute'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/attribute_assignment.rb:21:in `block in _assign_attributes'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/attribute_assignment.rb:13:in `each'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/attribute_assignment.rb:13:in `_assign_attributes'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activemodel-7.0.4.3/lib/active_model/attribute_assignment.rb:34:in `assign_attributes'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/persistence.rb:768:in `block in update'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/persistence.rb:767:in `update'
/opt/exercism/website/app/commands/git/sync_exercise_approaches.rb:11:in `call'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/mandate-2.2.0/lib/mandate/call_injector.rb:10:in `call'
/opt/exercism/website/app/commands/git/sync_practice_exercise.rb:31:in `call'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/mandate-2.2.0/lib/mandate/call_injector.rb:10:in `call'
/opt/exercism/website/app/commands/git/sync_track.rb:136:in `block in sync_practice_exercises!'
/opt/exercism/website/app/commands/git/sync_track.rb:117:in `each'
/opt/exercism/website/app/commands/git/sync_track.rb:117:in `each_with_index'
/opt/exercism/website/app/commands/git/sync_track.rb:117:in `sync_practice_exercises!'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/mandate-2.2.0/lib/mandate/memoize.rb:47:in `block (2 levels) in __mandate_memoize'
/opt/exercism/website/app/commands/git/sync_track.rb:40:in `call'
/opt/exercism/website/config/initializers/mandate.rb:39:in `perform'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/execution.rb:59:in `block in _perform_job'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/bugsnag-6.25.2/lib/bugsnag/integrations/rails/active_job.rb:38:in `block (2 levels) in included'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.1/lib/i18n.rb:322:in `with_locale'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/execution.rb:58:in `_perform_job'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:20:in `_perform_job'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/execution.rb:46:in `perform_now'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:14:in `block in perform_now'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:25:in `block in instrument'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `block in instrument'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:206:in `instrument'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:35:in `instrument'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/instrumentation.rb:14:in `perform_now'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/logging.rb:18:in `block in perform_now'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:37:in `tagged'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/tagged_logging.rb:99:in `tagged'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/logging.rb:25:in `tag_logger'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/logging.rb:18:in `perform_now'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/execution.rb:24:in `block in execute'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/reloader.rb:72:in `block in wrap'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/execution_wrapper.rb:88:in `wrap'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/reloader.rb:71:in `wrap'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `instance_exec'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/callbacks.rb:138:in `run_callbacks'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/execution.rb:22:in `execute'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activejob-7.0.4.3/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:210:in `execute_job'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:180:in `block (4 levels) in process'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:180:in `traverse'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/bugsnag-6.25.2/lib/bugsnag/integrations/sidekiq.rb:24:in `call'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/metrics/tracking.rb:26:in `track'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/metrics/tracking.rb:122:in `call'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-failures-1.0.4/lib/sidekiq/failures/middleware.rb:9:in `call'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/skylight-5.3.4/lib/skylight/sidekiq.rb:33:in `block in call'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/skylight-5.3.4/lib/skylight.rb:150:in `block in trace'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/skylight-5.3.4/lib/skylight/instrumenter.rb:224:in `trace'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/skylight-5.3.4/lib/skylight.rb:149:in `trace'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/skylight-5.3.4/lib/skylight/sidekiq.rb:32:in `call'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:182:in `traverse'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/middleware/chain.rb:173:in `invoke'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:179:in `block (3 levels) in process'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:140:in `block (6 levels) in dispatch'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/job_retry.rb:114:in `local'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:139:in `block (5 levels) in dispatch'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/rails.rb:16:in `block in call'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/reloader.rb:72:in `block in wrap'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/reloader.rb:71:in `wrap'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/rails.rb:15:in `call'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:135:in `block (4 levels) in dispatch'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:271:in `stats'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:130:in `block (3 levels) in dispatch'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/job_logger.rb:13:in `call'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:129:in `block (2 levels) in dispatch'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/job_retry.rb:81:in `global'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:128:in `block in dispatch'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/job_logger.rb:39:in `prepare'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:127:in `dispatch'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:177:in `handle_interrupt'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:177:in `block in process'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:176:in `handle_interrupt'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:176:in `process'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:82:in `process_one'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/processor.rb:72:in `run'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/component.rb:10:in `watchdog'
/opt/exercism/website/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.4/lib/sidekiq/component.rb:19:in `block in safe_thread'
```

Please tag @exercism/maintainers-admin if you require more information.

**Comment by meatball133** [comment]
@exercism/maintainers-admin, I would like more info

**Comment by meatball133** [comment]
We do have a duplicate glitch

**Comment by ErikSchierboom** [comment]
> @exercism/maintainers-admin, I would like more info

The opening post contains a link to the corresponding commit: https://github.com/exercism/crystal/commit/8cb214fe2f51d1f767e145bde2754c2a37475eb5I

> We do have a duplicate glitch

Ah yes, I see that you changed a `uuid`. This is not easily fixable in the database. I would suggest to revert the commit as the UUID might not be unique, but it's used in different tables so it doesn't actually matter much.

We should update `configlet` to ensure that the UUID is unique across the track.

**Comment by meatball133** [comment]
The old one wasnt unique but this new one is. Should I still reverse it?

**Comment by ErikSchierboom** [comment]
Was it not unique for the approaches?

**Comment by meatball133** [comment]
It was a duplicate of a uuid approach on the python track

**Comment by ErikSchierboom** [comment]
Aha. Then I'll have to do some manual work. I'll let you know

**Comment by ErikSchierboom** [comment]
I've fixed it in the database.
